server:
  port: 8090
---
spring:
  application:
    name: doldolseo_msa_gw
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

#      default-filters:
#        - name: GlobalFilter
#          args:
#            baseMessage: Spring Cloud Gateway GlobalFilter
#            preLogger: true
#            postLogger: true
#      routes:
#        - id: doldolseo-review
#          uri: http://localhost:8080/
#          predicates:
#            - Path=/doldolseo/review/**
#          filters:
#            - name: TestFilter
#              args:
#                baseMessage: \uB3CC\uB3CC\uC11C \uD14C\uC2A4\uD2B8\uD544\uD130 \uC785\uB2C8\uB2E4.
#                preLogger: true
#                postLogger: true

---
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY