server:
  port: 9000
---
spring:
  application:
    name: doldolseo_msa_gw
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      discovery:
        locator:
          enabled: false
---
jwt:
  secret: DOLDOLSEOTESTSECRET
  api-key: DOLDOLSEOTESTAPIKEY
---
