server:
  port: 9000
#  ssl:
#    key-store: classpath:tutorial.jks
#    key-store-type: pkcs12
#    key-store-password: kyeongil7823!
#    key-password: kyeongil7823!
#    key-alias: tutorial
---
spring:
  application:
    name: doldolseo_msa_gw
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      discovery:
        locator:
          enabled: false
---
jwt:
  secret: DOLDOLSEOTESTSECRET
  api-key: DOLDOLSEOTESTAPIKEY
---